### ISSUE TITLE
data error: media.zip

### ISSUE THREAD

**Issue by kkakkkka** [GeWu-Lab/Ref-AVS#1]
warning [media.zip]:  11836697169 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [media.zip]:  start of central directory not found;

**Comment by kkakkkka** [comment]
I have checked the settings again. The media.zip downloaded from Zenodo (https://zenodo.org/records/12737763/files/media.zip?download=1) does not work on Mac or Ubuntu.

**Comment by yaotingwangofficial** [comment]
Repacked dataset: https://zenodo.org/records/12970978/files/RefAVSBench.tar.gz?download=1

Please download with `wget https://zenodo.org/records/12970978/files/RefAVSBench.tar.gz?download=1` and rename it with `mv RefAVSBench.tar.gz?download=1 RefAVSBench.tar.gz`.

It works on my linux end, many thanks.

**Comment by yaotingwangofficial** [comment]
Repacked dataset: https://zenodo.org/records/12970978/files/RefAVSBench.tar.gz?download=1

Please download with `wget https://zenodo.org/records/12970978/files/RefAVSBench.tar.gz?download=1` and rename it with `mv RefAVSBench.tar.gz?download=1 RefAVSBench.tar.gz`.

It works on my linux end, many thanks.
