### ISSUE TITLE
audio bitrate?

### ISSUE THREAD

**Issue by Divine0719** [GeWu-Lab/Ref-AVS#2]
Hi
During the training process, there was an issue as shown in the figure. After our investigation, we found that all audio starting with ’null ‘ had a bit rate of 705, while others had a bit rate of 1536.
![1725520364350](https://github.com/user-attachments/assets/38510694-6752-4a78-9e7f-d435ff81625d)
![d1cbb2bf00d147a0bac4f9699f3422a](https://github.com/user-attachments/assets/b01279cb-e876-4699-b4cf-70d2bd658b67)
![60fba4ab4313fe768c8b78f7932174b](https://github.com/user-attachments/assets/f512b2bb-f463-4958-9016-59eb981984d0)

This has led to the above error, but we don't know how to modify it. Currently, we can only use batch size=1 to avoid stacking different data and temporarily avoid errors. We hope to get your help

Thank you！

**Comment by yaotingwangofficial** [comment]
Dear Divine,

The towhee should generate fixed embedding length with corresponding audio clip length in "second", which means for all audio samples with 10s length should have the same vggish embedding length, even with different sample rate.

Regarding to their source code https://towhee.io/audio-embedding/vggish/src/branch/main/vggish_input.py  (check line 47), this pipeline executes resample before the vggish forwarding. 

I also checked in my linux end with the below code and it works fine:
```
from towhee import pipe, ops
import torch

audio_vggish_pipeline = (   # pipeline building
            pipe.input('path')
                .map('path', 'frame', ops.audio_decode.ffmpeg())
                .map('frame', 'vecs', ops.audio_embedding.vggish())
                .output('vecs')
        )

prefix = '/ibex/user/wangy1l/dataset/audiovisual'

_id = 'null_m-KXvmc3dLn3E_1060000_1070000'
_p = f'{prefix}/REFAVS/media/{_id}/audio.wav'
audio_emb = torch.tensor(audio_vggish_pipeline(_p).get()[0])
print(f'{_id}: {audio_emb.shape}')  # (10, 128)

_id = 'szPF0KhxYIs_301000_311000'
_p = f'{prefix}/REFAVS/media/{_id}/audio.wav'
audio_emb = torch.tensor(audio_vggish_pipeline(_p).get()[0])
print(f'{_id}: {audio_emb.shape}')  # (10, 128)

""" print output
null_m-KXvmc3dLn3E_1060000_1070000: torch.Size([10, 128])
szPF0KhxYIs_301000_311000: torch.Size([10, 128])
"""
```

Could you please check your code logic / dataloader / towhee dependency? 
(BTW, if you did not use towhee to get the vggish feature, you can just resample all audio clips to specific sample rate.)

**Comment by VoyageWang** [comment]
however， I got the same problems， maybe it is the problem when contact with shape [20, 128] with [10,128]

**Comment by yaotingwangofficial** [comment]
I just found that torchaudio can also support VGGish. You can check it out at this link: [VGGishBundle](https://pytorch.org/audio/main/generated/torchaudio.prototype.pipelines.VGGishBundle.html).

You can take a look at the sample rate (44100, 44.1 kHz) of the audio files obtained from the null set which generate [10, 128] embeddings. Then when you loading audio from other subsets, you can specify the sample rate. You can do this as follows:

```
wav, sr = torchaudio.load(wav_path)
torchaudio.functional.resample(wav, 44100, input_sr)
```

If it can resolve the question, please give any reactions to let me know, appreciate it!

**Comment by yaotingwangofficial** [comment]
Also please check if you are using a stereo channel to obtain the waveform.
To use mono data, you can try waveform = waveform[0] to convert waveform like [2, 441882] to [1, 441882].

![image](https://github.com/user-attachments/assets/906dc692-47e2-4f3d-a564-f94f35d58b9d)
